version: 2
formats: [pdf, htmlzip]

build:
  os: ubuntu-24.04
  tools: {python: "3.11"}
  jobs: {pre_install: [pip install 'mkdocs>=1.6.1' 'mkdocs-codeinclude-plugin>=0.2.1']}

mkdocs:
  configuration: mkdocs.yml
