name: Run Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version:
          - "3.11"
    steps:
    - uses: actions/checkout@v4
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true
        cache: pip
    - name: Install workflow dependencies
      run: pip install rust-just uv
    - name: Run tests
      run: just test
