name: Run Tests
on: [push, pull_request]

jobs:
  test:  # name of the job
    runs-on: "${{ matrix.name }}"
    timeout-minutes: 10
    strategy:
      max-parallel: 6
      matrix: {name: [ubuntu-py311,ubuntu-py314]}
    steps:
    - uses: actions/checkout@v5

    - name: Install workflow dependencies
      run:  pip install rust-just

    - name: Run tests
      run:  just test
